---
# tasks file for keystone DB Setup

- name: DB sync for keystone.
  command: >
    keystone-manage db_sync
  become: yes
  become_user: "{{ keystone_system_user_name }}"
  ignore_errors: True
  run_once: True
